import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TopBar from "@/components/header/TopBar";
import {
  Box,
  Card,
  CardContent,
  Container,
  Divider,
  Grid,
} from "@mui/material";
import AppBar from "@/components/header/AppBar";
import AppBar2 from "@/components/header/AppBar2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          minHeight: "100vh",
          backgroundColor: "#fff",
        }}
      >
        <TopBar />
        <AppBar />
        <AppBar2 />
        <Container>
          <Divider />
        </Container>
        <Container sx={{ mt: 2 }}>
          <Grid container>
            <Grid item md={2}>
              <Card>
                <CardContent></CardContent>
              </Card>
            </Grid>
            <Grid item md={10}></Grid>
          </Grid>
        </Container>
      </Box>
    </Box>
  );
}
